input("Enter the number of labs completed: ")
input("Enter the number of quizzes completed: ")
input("Enter grade for Assignment 1: ")
input("Enter grade for Assignment 2: ")
input("Enter grade for Assignment 3: ")
input("Enter grade for Assignment 4: ")
input("Enter grade for Midterm 1: ")
input("Enter grade for Midterm 2: ")
input("Enter grade for Final Exam: ")
input("Enter grade for Midterms and Final Preparation: ")
